name: Build/release

on:
    push:
        tags:
            - '*'

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v1

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            - name: build
              run: |
                  npm install
                  node init.js
                  npm run build
                  zip -r xlinkote_${{ github.ref_name }}.zip dist

            - name: upload
              uses: actions/upload-artifact@v3
              with:
                  path: "*.zip"

            - name: release
              uses: softprops/action-gh-release@v1
              with:
                  files: "*.zip"
                  draft: true
              env:
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
